// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBql1eGH2AqCPARMkM4sgmKSjfWKYT-es4',
    appId: '1:459643024950:web:29467854b4481f4e5b8a97',
    messagingSenderId: '459643024950',
    projectId: 'kinton-82dc9',
    authDomain: 'kinton-82dc9.firebaseapp.com',
    databaseURL: 'https://kinton-82dc9-default-rtdb.firebaseio.com',
    storageBucket: 'kinton-82dc9.appspot.com',
    measurementId: 'G-45DSN6ERHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCATE_2jrBL0oG_j0rqTrKw_ofsbeM5cmY',
    appId: '1:459643024950:android:5239f7decf311fc25b8a97',
    messagingSenderId: '459643024950',
    projectId: 'kinton-82dc9',
    databaseURL: 'https://kinton-82dc9-default-rtdb.firebaseio.com',
    storageBucket: 'kinton-82dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8wUsEZFdyz8eHit11j3ABsjwVPQx-aCc',
    appId: '1:459643024950:ios:d94147aca969931e5b8a97',
    messagingSenderId: '459643024950',
    projectId: 'kinton-82dc9',
    databaseURL: 'https://kinton-82dc9-default-rtdb.firebaseio.com',
    storageBucket: 'kinton-82dc9.appspot.com',
    iosClientId: '459643024950-joqbr52k8rmp3g44sn0jou2lmf91254r.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8wUsEZFdyz8eHit11j3ABsjwVPQx-aCc',
    appId: '1:459643024950:ios:d94147aca969931e5b8a97',
    messagingSenderId: '459643024950',
    projectId: 'kinton-82dc9',
    databaseURL: 'https://kinton-82dc9-default-rtdb.firebaseio.com',
    storageBucket: 'kinton-82dc9.appspot.com',
    iosClientId: '459643024950-joqbr52k8rmp3g44sn0jou2lmf91254r.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
