# platform :ios, '9.0'

target 'Runner' do
 use_frameworks!
 use_modular_headers!

 flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
 # target 'RunnerTests' do <-- MAKE SURE THIS LINE IS COMMENTED OUT
  # inherit! :search_paths <-- MAKE SURE THIS LINE IS COMMENTED OUT
 # end <-- MAKE SURE THIS LINE IS COMMENTED OUT
end
